### ISSUE TITLE
feat(resources): migrate to data classes

### ISSUE THREAD

**Issue by paguos** [paguos/transfermarkt-py#8]
Migrate the exiting functionality of the `list_competitions` and `list_clubs` to use [data classes](https://realpython.com/python-data-classes/)

**Tasks**

- [ ] Add the **competition** data class
- [ ] Add the **club** data class
- [ ] Delete the `GenericStruct` class
- [ ] Adjust the   `list_competitions` method
- [ ] Adjust the   `list_clubs ` method
